### ISSUE TITLE
Configuración inicial de la base de datos Cassandra

### ISSUE THREAD

**Issue by javivm17** [Full-Tortuga/decide-full-tortuga-almacenamiento#3]
Se busca mejorar el rendimiento de la aplicación migrando la base de datos actual, hacia una no relacional.

La solución propuesta es integrar Cassandra como base de datos, sustituyendo así a Postgresql, ya que Cassandra es capaz de almacenar grandes cantidades de datos.

Se han barajado como alternativas las siguientes bases de datos: MongoDB y hacer uso de un hosting gratuito de MongoDB.

**Comment by Javitoox** [comment]
Esta tarea ha sido cerrada tras decidir no usar Cassandra en nuestro proyecto
